import org.jetbrains.kotlin.gradle.dsl.KotlinCommonOptions
import org.jetbrains.kotlin.gradle.plugin.KotlinCompilation
import org.jetbrains.kotlin.gradle.plugin.KotlinCompilationToRunnableFiles

plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
    application
}

kotlin {
    jvm {
        withJava()
    }
    sourceSets {
        val jvmMain by getting {
//            kotlin.srcDir("src")
//            resources.srcDir("resources")

            dependencies {
                implementation(project(":serverModels"))
                extra.libsAt(listOf(
                    "kotlin.serializationJson",
                    "kotlin.stdLib",
                    "ktor.server.netty",
                    "ktor.server.core",
                    "ktor.server.logback",
                    "ktor.auth",
                    "ktor.metrics",
                    "ktor.websockets",
                    "ktor.gson"
                )).forEach { implementation(it) }
            }
        }
    }
}

//task<JavaExec>("run") {
//    main = "com.well.server.ApplicationKt"
//    val jvm by kotlin.targets.getting
//    val main: KotlinCompilation<KotlinCommonOptions> by jvm.compilations
//    val runtimeDependencies = (main as KotlinCompilationToRunnableFiles<KotlinCommonOptions>).runtimeDependencyFiles
//    classpath = files(main.output.allOutputs, runtimeDependencies)
//}

//tasks.create("stage") {
//    dependsOn(tasks.getByName("installDist"))
//}
//
//application {
//    mainClass.set("ApplicationKt")
//}
//
//distributions {
//    main {
//        contents {
//            from("$buildDir/libs") {
//                rename("${rootProject.name}-jvm", rootProject.name)
//                into("lib")
//            }
//        }
//    }
//}
//
//tasks.getByName<Jar>("jar") {
//    manifest {
//        attributes(
//            "Main-Class" to "com.well.server.ApplicationKt",
//            "Class-Path" to "./lib/*"
//        )
//    }
//}

//tasks.jar {
//    archiveVersion.set("")
//    manifest {
//        attributes(
//            "Main-Class" to "importer.MetDataImportWizard",
//            "Class-Path" to "./lib/*"
//        )
//    }
//}

//tasks.getByName<JavaExec>("run") {
//    classpath(tasks.getByName<Jar>("jvmJar")) // so that the JS artifacts generated by `jvmJar` can be found and served
//    main = "com.well.server.ApplicationKt"
//    val jvm by kotlin.targets.getting
//    val main: KotlinCompilation<KotlinCommonOptions> by jvm.compilations
//    val runtimeDependencies = (main as KotlinCompilationToRunnableFiles<KotlinCommonOptions>).runtimeDependencyFiles
//    classpath = files(main.output.allOutputs, runtimeDependencies)
//}